### ISSUE TITLE
Please specify the build environment.

### ISSUE THREAD

**Issue by mafrmt00** [OliWright/PicoVectorscopeExamples#4]
I am using the Pi Pico SDK on macOS.
This means GCC 10.3.1 arm-none-eabi.

The build fails with the following errors:
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp: In member function 'virtual void SpinnyCubeDemo::UpdateAndRender(DisplayList&, float)':
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:111:42: error: call of overloaded 'FixedPoint(uint32_t&)' is ambiguous
[build]   111 |                  x + (gap * 0.5f * (IntT)i), y + (gap * 0.7f * (IntT)i), z + (gap * 0.8f * (IntT)i),
[build]       |                                          ^
[build] In file included from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/displaylist.h:29,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/demo.h:46,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/picovectorscope.h:27,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:21:
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:202:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(uint) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false; uint = unsigned int]'
[build]   202 |     constexpr FixedPoint(uint rhs) : m_storage(rhs << kNumFractionalBits) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:199:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(int) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false]'
[build]   199 |     constexpr FixedPoint(int rhs) : m_storage((StorageType)(int)((uint)rhs << kNumFractionalBits)) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:196:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(float) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false]'
[build]   196 |     constexpr FixedPoint(float rhs) : m_storage(fromOtherFormat(rhs).getStorage()) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:193:24: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::StorageType) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false; FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::StorageType = long int]'
[build]   193 |     explicit constexpr FixedPoint(StorageType storage) : m_storage(storage) {}
[build]       |                        ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:157:7: note: candidate: 'constexpr FixedPoint<6, 0, long int, long int, false>::FixedPoint(const FixedPoint<6, 0, long int, long int, false>&)'
[build]   157 | class FixedPoint
[build]       |       ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:157:7: note: candidate: 'constexpr FixedPoint<6, 0, long int, long int, false>::FixedPoint(FixedPoint<6, 0, long int, long int, false>&&)'
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:111:70: error: call of overloaded 'FixedPoint(uint32_t&)' is ambiguous
[build]   111 |                  x + (gap * 0.5f * (IntT)i), y + (gap * 0.7f * (IntT)i), z + (gap * 0.8f * (IntT)i),
[build]       |                                                                      ^
[build] In file included from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/displaylist.h:29,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/demo.h:46,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/picovectorscope.h:27,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:21:
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:202:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(uint) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false; uint = unsigned int]'
[build]   202 |     constexpr FixedPoint(uint rhs) : m_storage(rhs << kNumFractionalBits) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:199:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(int) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false]'
[build]   199 |     constexpr FixedPoint(int rhs) : m_storage((StorageType)(int)((uint)rhs << kNumFractionalBits)) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:196:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(float) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false]'
[build]   196 |     constexpr FixedPoint(float rhs) : m_storage(fromOtherFormat(rhs).getStorage()) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:193:24: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::StorageType) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false; FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::StorageType = long int]'
[build]   193 |     explicit constexpr FixedPoint(StorageType storage) : m_storage(storage) {}
[build]       |                        ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:157:7: note: candidate: 'constexpr FixedPoint<6, 0, long int, long int, false>::FixedPoint(const FixedPoint<6, 0, long int, long int, false>&)'
[build]   157 | class FixedPoint
[build]       |       ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:157:7: note: candidate: 'constexpr FixedPoint<6, 0, long int, long int, false>::FixedPoint(FixedPoint<6, 0, long int, long int, false>&&)'
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:111:98: error: call of overloaded 'FixedPoint(uint32_t&)' is ambiguous
[build]   111 |                  x + (gap * 0.5f * (IntT)i), y + (gap * 0.7f * (IntT)i), z + (gap * 0.8f * (IntT)i),
[build]       |                                                                                                  ^
[build] In file included from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/displaylist.h:29,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/demo.h:46,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/picovectorscope.h:27,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:21:
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:202:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(uint) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false; uint = unsigned int]'
[build]   202 |     constexpr FixedPoint(uint rhs) : m_storage(rhs << kNumFractionalBits) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:199:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(int) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false]'
[build]   199 |     constexpr FixedPoint(int rhs) : m_storage((StorageType)(int)((uint)rhs << kNumFractionalBits)) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:196:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(float) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false]'
[build]   196 |     constexpr FixedPoint(float rhs) : m_storage(fromOtherFormat(rhs).getStorage()) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:193:24: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::StorageType) [with int numWholeBits = 6; int numFractionalBits = 0; TStorageType = long int; TIntermediateStorageType = long int; bool doClamping = false; FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::StorageType = long int]'
[build]   193 |     explicit constexpr FixedPoint(StorageType storage) : m_storage(storage) {}
[build]       |                        ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:157:7: note: candidate: 'constexpr FixedPoint<6, 0, long int, long int, false>::FixedPoint(const FixedPoint<6, 0, long int, long int, false>&)'
[build]   157 | class FixedPoint
[build]       |       ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:157:7: note: candidate: 'constexpr FixedPoint<6, 0, long int, long int, false>::FixedPoint(FixedPoint<6, 0, long int, long int, false>&&)'
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:112:57: error: conversion from 'long unsigned int' to 'Vector3<FixedPoint<12, 16, long int, long long int, false> >::ScalarType' {aka 'FixedPoint<12, 16, long int, long long int, false>'} is ambiguous
[build]   112 |                  StandardFixedTranslationVector(0, 0, 2 + i * 4));
[build]       |                                                       ~~^~~~~~~
[build] In file included from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/displaylist.h:29,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/demo.h:46,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/picovectorscope.h:27,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:21:
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:202:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(uint) [with int numWholeBits = 12; int numFractionalBits = 16; TStorageType = long int; TIntermediateStorageType = long long int; bool doClamping = false; uint = unsigned int]'
[build]   202 |     constexpr FixedPoint(uint rhs) : m_storage(rhs << kNumFractionalBits) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:199:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(int) [with int numWholeBits = 12; int numFractionalBits = 16; TStorageType = long int; TIntermediateStorageType = long long int; bool doClamping = false]'
[build]   199 |     constexpr FixedPoint(int rhs) : m_storage((StorageType)(int)((uint)rhs << kNumFractionalBits)) {}
[build]       |               ^~~~~~~~~~
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/fixedpoint.h:196:15: note: candidate: 'constexpr FixedPoint<numWholeBits, numFractionalBits, TStorageType, TIntermediateStorageType, doClamping>::FixedPoint(float) [with int numWholeBits = 12; int numFractionalBits = 16; TStorageType = long int; TIntermediateStorageType = long long int; bool doClamping = false]'
[build]   196 |     constexpr FixedPoint(float rhs) : m_storage(fromOtherFormat(rhs).getStorage()) {}
[build]       |               ^~~~~~~~~~
[build] In file included from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/displaylist.h:30,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/demo.h:46,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/picovectorscope.h:27,
[build]                  from /Users/mafrmt00/source/PicoVectorscopeExamples/src/cube.cpp:21:
[build] /Users/mafrmt00/source/PicoVectorscopeExamples/PicoVectorscope/include/types.h:42:62: note:   initializing argument 3 of 'constexpr Vector3<T>::Vector3(Vector3<T>::ScalarType, Vector3<T>::ScalarType, Vector3<T>::ScalarType) [with T = FixedPoint<12, 16, long int, long long int, false>; Vector3<T>::ScalarType = FixedPoint<12, 16, long int, long long int, false>]'
[build]    42 |     constexpr Vector3(ScalarType x, ScalarType y, ScalarType z) : x(x), y(y), z(z) {}
[build]       |                                                   ~~~~~~~~~~~^
[build] [50/95  44% :: 4.266] Building CXX object CMakeFiles/vectorscope.dir/src/starfield.cpp.obj
[build] [50/95  45% :: 4.266] Building CXX object CMakeFiles/vectorscope.dir/src/textmode.cpp.obj
[build] [50/95  46% :: 4.267] Building C object CMakeFiles/vectorscope.dir/Users/mafrmt00/source/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
[build] [50/95  47% :: 4.267] Building C object CMakeFiles/vectorscope.dir/Users/mafrmt00/source/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
[build] [50/95  48% :: 4.302] Building C object CMakeFiles/vectorscope.dir/Users/mafrmt00/source/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
[build] [50/95  49% :: 4.353] Building CXX object CMakeFiles/vectorscope.dir/PicoVectorscope/extras/src/shapes3d.cpp.obj
[build] [50/95  50% :: 4.510] Building C object CMakeFiles/vectorscope.dir/Users/mafrmt00/source/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
[build] [50/95  51% :: 4.787] Building CXX object CMakeFiles/vectorscope.dir/src/invadersfromspace.cpp.obj
[build] [50/95  52% :: 4.863] Building CXX object CMakeFiles/vectorscope.dir/src/spacerocksinspace.cpp.obj
[build] ninja: build stopped: subcommand failed.

**Comment by OliWright** [comment]
Apologies @mafrmt00, it looks like I haven't correctly updated the PicoVectorscope framework submodule.  I'm AFK right now - but I'll get to it as soon as I can.

**Comment by OliWright** [comment]
In the meantime, you could try `cd`ing into the `PicoVectorscope` directory, and doing `git checkout main` and `git pull` for luck.

**Comment by OliWright** [comment]
No, the issue was that I pushed my fix yesterday to the wrong branch.  I think it should be fixed now.

**Comment by mafrmt00** [comment]
That fixed it.
Thank You
