### ISSUE TITLE
I had some fun today. Thank You!

### ISSUE THREAD

**Issue by mafrmt00** [OliWright/PicoVectorscopeExamples#6]
Since I first laid hands on a oscilloscope, I always wanted to use it as a display for games.

But I never thought, it would work that good!

Thanks

![0B64EB91-CF57-42E9-B660-B2A0DEB58399](https://github.com/OliWright/PicoVectorscopeExamples/assets/11454230/a33e1b9b-8d6d-4ba8-b400-4a4dc7d95fa9)

![A272A5B8-52C2-4EE4-BC82-2D331BE6E5B5](https://github.com/OliWright/PicoVectorscopeExamples/assets/11454230/8d1d1e8c-1c6f-48f0-b727-8ca614dea9c4)

**Comment by OliWright** [comment]
Oh fantastic!  ~~I'd love to see a video of it working.~~
I see you linked a video in the first post.  Looks great 👍

**Comment by OliWright** [comment]
Hey @mafrmt00,
I haven't updated it in a while - but here's a work-in-progress...
https://github.com/OliWright/SpaceTanks  (actually it looks like I need to push an update to it)
![image](https://github.com/OliWright/PicoVectorscopeExamples/assets/8660395/c506d26e-76f8-43ce-848c-b02e6057faf1)
